# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.1

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

#readonlyrest - disabled for now
#COPY readonlyrest-1.16.9_es5.5.1.zip .
#RUN bin/elasticsearch-plugin install file:/usr/share/elasticsearch/readonlyrest-1.16.9_es5.5.1.zip
